import PDFDocument from "pdfkit";

export function generateAnalyticsPdf(data, res) {

    const doc = new PDFDocument({
        margin: 50,
        size: "A4"
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=analytics-report.pdf");

    doc.pipe(res);


    /* =================================
       HEADER
    ================================= */

    doc
        .fontSize(24)
        .fillColor("#111827")
        .text("ABI Analytics Report", { align: "center" });

    doc.moveDown(0.5);

    doc
        .fontSize(10)
        .fillColor("#6b7280")
        .text(`Generated on ${new Date().toLocaleString()}`, { align: "center" });

    doc.moveDown(2);


    /* =================================
       KPI SUMMARY
    ================================= */

    doc
        .fontSize(18)
        .fillColor("#111827")
        .text("Business KPI Summary");

    doc.moveDown(1);

    doc
        .fontSize(12)
        .fillColor("#000000");

    doc.text(`Total Revenue : $${Number(data.kpis.totalRevenue).toLocaleString()}`);
    doc.text(`Total Sales   : ${Number(data.kpis.totalSales).toLocaleString()}`);
    doc.text(`Net Profit    : $${Number(data.kpis.totalProfit).toLocaleString()}`);

    doc.moveDown(2);


    /* =================================
       REVENUE TREND
    ================================= */

    doc
        .fontSize(18)
        .fillColor("#111827")
        .text("Monthly Revenue Trend");

    doc.moveDown(1);

    data.revenueTrend.forEach(item => {
        doc.fontSize(11).text(`${item.month} : $${Number(item.revenue).toLocaleString()}`);
    });

    doc.moveDown(2);


    /* =================================
       SALES BY CITY
    ================================= */

    doc
        .fontSize(18)
        .fillColor("#111827")
        .text("Top Performing Cities");

    doc.moveDown(1);

    data.citySales.forEach(item => {
        doc.fontSize(11).text(`${item.name} : ${Number(item.sales).toLocaleString()} units sold`);
    });

    doc.moveDown(2);


    /* =================================
       AI INSIGHTS
    ================================= */

    doc
        .fontSize(18)
        .fillColor("#111827")
        .text("AI Generated Insights");

    doc.moveDown(1);

    const insights = [
        "Revenue has shown consistent growth over the analyzed period.",
        "Top cities contribute significantly to overall sales performance.",
        "Profitability remains stable across recent business operations.",
        "Monitoring inventory and regional sales trends can further improve forecasting accuracy."
    ];

    insights.forEach(insight => {
        doc.fontSize(11).text(`• ${insight}`);
    });

    doc.moveDown(3);


    /* =================================
       FOOTER
    ================================= */

    doc
        .fontSize(10)
        .fillColor("#6b7280")
        .text("Generated by Agentic Business Intelligence Multilingual SQL Analyst", {
            align: "center"
        });

    doc.end();
}